[build]
  publish = "."
  functions = "netlify/functions"

[functions."ebay-price"]
  timeout = 26

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
